#!/bin/sh
TEMP=$(awk '{printf "%.1f°C", $1/1000}' /sys/class/thermal/thermal_zone0/temp 2>/dev/null || echo "N/A")
UPTIME=$(uptime -p | sed 's/up //')
LOAD=$(cut -d' ' -f1-3 /proc/loadavg)

printf "\n  maelthra // homelab\n"
printf "  up %s  |  load %s  |  cpu %s\n\n" "$UPTIME" "$LOAD" "$TEMP"
